# Generated by Django 4.1.7 on 2023-03-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
