# Generated by Django 4.1.7 on 2023-03-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_set', models.FileField(upload_to='datasetfile')),
                ('accuracy', models.FloatField(null=True)),
                ('precision', models.FloatField(null=True)),
                ('recall', models.FloatField(null=True)),
                ('f1_score', models.FloatField(null=True)),
                ('algo', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'dataset_details',
            },
        ),
    ]
