# Generated by Django 4.1.7 on 2023-03-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_predict_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='conclusion',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
