# Generated by Django 4.1.7 on 2023-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_predict_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='Competitors',
            field=models.IntegerField(null=True),
        ),
    ]
